/*
 * demos/mmap_demo.c
 *
 * Demonstrates mmap() — maps a file into the process virtual address space.
 *
 * What to observe in KernelScope:
 *   1. Run this program — note the PID printed.
 *   2. Paste the PID into KernelScope.
 *   3. Panel 1 (Memory Map) will show a new VMA labelled with the tmp file path.
 *   4. The VMA has permissions rw-p (MAP_SHARED, writable).
 *   5. After 20 seconds the program calls munmap() and the VMA vanishes.
 *
 * Kernel internals:
 *   mmap(2) → sys_mmap() → do_mmap() → vm_mmap_pgoff()
 *   Creates a new vm_area_struct and inserts it into mm->mm_rb.
 *   /proc/<pid>/maps is generated by show_map() in fs/proc/task_mmu.c
 *   which walks the mm_struct's red-black tree of VMAs.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/stat.h>

#define MAP_SIZE 4096

int main(void) {
    /* Create a temporary file */
    char tmpfile[] = "/tmp/ks_mmap_XXXXXX";
    int fd = mkstemp(tmpfile);
    if (fd < 0) {
        perror("mkstemp");
        return 1;
    }

    /* Ensure the file is exactly MAP_SIZE bytes */
    if (ftruncate(fd, MAP_SIZE) != 0) {
        perror("ftruncate");
        close(fd);
        unlink(tmpfile);
        return 1;
    }

    /* MAP_SHARED: writes to addr are visible in the file immediately.
     * MAP_PRIVATE would give copy-on-write semantics instead.
     * PROT_READ | PROT_WRITE → vm_flags VM_READ | VM_WRITE in the VMA */
    void *addr = mmap(NULL, MAP_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (addr == MAP_FAILED) {
        perror("mmap");
        close(fd);
        unlink(tmpfile);
        return 1;
    }

    printf("=== KernelScope mmap Demo ===\n");
    printf("PID:             %d\n",   getpid());
    printf("Temp file:       %s\n",   tmpfile);
    printf("Mapped address:  %p\n",   addr);
    printf("Mapped size:     %d bytes\n", MAP_SIZE);
    printf("\n");
    printf(">> Writing through the mapping (no write() syscall needed)...\n");

    /* Write directly through the mapping — no write() syscall */
    snprintf((char *)addr, MAP_SIZE,
             "Written by PID %d via mmap() — "
             "this string is now in the file without any write() syscall!",
             getpid());

    /* msync flushes dirty pages back to the file on disk */
    if (msync(addr, MAP_SIZE, MS_SYNC) != 0) {
        perror("msync");
    }

    printf(">> Written! Now check:\n");
    printf("   KernelScope Panel 1 (Memory Map) for PID %d\n", getpid());
    printf("   Look for the VMA containing: %s\n", tmpfile);
    printf("   Permissions should be: rw-p  (read+write, private copy-on-write)\n");
    printf("\n");
    printf(">> Sleeping 20 seconds — inspect the maps panel now...\n");
    fflush(stdout);

    sleep(20);

    printf("\n>> Reading back through the mapping: \"%.80s\"\n", (char *)addr);
    printf(">> Calling munmap()... VMA will disappear from /proc/%d/maps\n", getpid());
    fflush(stdout);

    munmap(addr, MAP_SIZE);
    close(fd);
    unlink(tmpfile);

    printf(">> Done. mmap VMA has been removed from the address space.\n");
    return 0;
}
